- hosts: all
  port: 22023
  remote_user: johannes
  sudo: yes
  tasks:
      - name: Add pycurl and jinja2 packages
        apt: pkg={{ item }} state=present
        with_items:
            - python-pycurl
            - python-jinja2
 
      - name: Add Tor repository
        apt_repository: repo="deb http://deb.torproject.org/torproject.org wheezy main" state=present

      - name: Add torproject GPG key
        shell: apt-key adv --recv-keys --keyserver keys.gnupg.net 886DDD89

      - name: Install Torproject Keyring
        apt: update_cache=yes install_recommends=no pkg=deb.torproject.org-keyring state=present

      - name: Install Tor geoip database
        apt: update_cache=yes install_recommends=no pkg={{item}}
        with_items:
            - tor
            - tor-geoipdb

      - name: Add users to debian-tor group
        user: name=johannes groups=debian-tor append=yes
            
      # -- snip -- for later on tor deployment of torrc-generator

      - name: Stop tor for maintenance
        service: name=tor state=stopped
        
      - name: for good measures, kill all tor processes
        shell: "killall tor || :"
       
      # -- snap for later on deployment of torrc-generator
      - name: Create torservers scripts and templates folders
        file: path={{ item }} owner=debian-tor group=debian-tor mode=750 state=directory
        with_items:
          - /opt/torservers/scripts
          - /opt/torservers/templates
        
      - name: Create directories for tor's controlport statements and auth cookies
        file: path={{ item }} owner=debian-tor group=debian-tor mode=750 state=directory
        with_items:
           - /var/run/torctl/statements
           - /var/run/torctl/cookies

      - name: Copy over torrc generator
        copy: src=tools/generate_tor_configurations.py dest=/opt/torservers/scripts/generate_tor_configurations.py
        
      - name: Copy over myfamily tool
        copy: src=tools/set_myfamily.py dest=/opt/torservers/scripts/set_myfamily.py

      - name: install pip
        apt: pkg=python-pip state=present

      - name: install stem for python
        pip: name=stem

      - name: Copy over fingerprint tool
        copy: src=tools/get_fingerprints.py dest=/opt/torservers/scripts/get_fingerprints.py

      - name: Copy over torrc template
        copy: src=config/torrc-multiproc dest=/opt/torservers/templates/tor_multiproc.tpl.cfg
         
      - name: Execute torrc generator with host params
        shell: "python /opt/torservers/scripts/generate_tor_configurations.py -a {{ relayips }} -n {{ relaynicks }} -c /opt/torservers/templates/tor_multiproc.tpl.cfg"

      - name: Copy multiproc-enabled torrc
        copy: src=config/initd-tor-multiproc dest=/etc/init.d/tor backup=yes
        
      - name: Make /etc/tor/ group-readable
        file: path=/etc/tor owner=debian-tor group=debian-tor mode=770 recurse=yes

      - name: Copy over torservers disclaimer site
        copy: src=config/exit_info.htm dest=/opt/torservers/exit_info.htm

      - name: Install unbound DNS Server
        apt: pkg=unbound state=installed

      - name: Activate unbound DNS Server
        shell: echo "nameserver 127.0.0.1" > /etc/resolv.conf

      - name: Start tor services
        service: name=tor state=started

      #
      # Install Munin Node
      #
      
      - name: Install munin node
        apt: pkg=munin-node state=present

      - name: Enable netstat plugin for munin
        file: src=/usr/share/munin/plugins/netstat dest=/etc/munin/plugins/netstat state=link
        
      - name: Remove http_loadtime plugin from munin
        file: path=/etc/munin/plugins/http_loadtime state=absent
 
      - name: Remove ntp plugins from munin
        file: path={{item}} state=absent
        with_fileglob: /etc/munin/plugins/ntp_* 
          
      - name: Remove postfix plugins from munin
        file: path={{item}} state=absent
        with_fileglob: /etc/munin/plugins/postfix_* 
 
      - name: Remove exim plugins from munin
        file: path={{item}} state=absent
        with_fileglob: /etc/munin/plugins/exim_* 
 
      - name: Allow torserver.net's munin collector
        shell: sed "s/allow \\^127\\\.0\\\.0\\\.1\\$/allow ^194\\\.150\\\.168\\\.61$/" -i /etc/munin/munin-node.conf

      - name: restart munin node
        service: name=munin-node state=restarted
