- hosts: all
  port: 22023
  remote_user: johannes
  sudo: yes
  tasks:
      - name: Add pycurl package
        apt: pkg=python-pycurl state=present
 
      - name: Add Tor repository
        apt_repository: repo="deb http://deb.torproject.org/torproject.org wheezy main" state=present

      - name: Add Tor Keyservers
        shell: apt-key adv --recv-keys --keyserver keys.gnupg.net 886DDD89

      - name: Install Torproject Keyring
        apt: update_cache=yes install_recommends=no pkg=deb.torproject.org-keyring state=present

      - name: Install Tor geoip database
        apt: update_cache=yes install_recommends=no pkg={{item}}
        with_items:
            - mercurial
            - tor
            - tor-geoipdb

      - name: Set username in hg config
        shell: echo "[ui]\nusername = Torservers Admin <admin@lists.torservers.net>" > ~/.hgrc

      - name: Initialize git in /etc/tor
        shell: cd /etc/tor && hg init

      - name: Stop tor for maintenance
        service: name=tor state=stopped

      - name: Add torservers torrc
        template: src=config/torrc dest=/etc/tor/torrc 

      - name: Add and commit torservers file to config repo
        shell: cd /etc/tor/ && hg add . && hg ci -m"Initial config."

      - name: Restart Relay
        service: name=tor state=started
