- hosts: all
  port: 2222
  remote_user: root
  tasks:
      - name: Install sudo package
        action: apt pkg=sudo state=latest

      - name: Add sudo group
        action: group name=sudo state=present


      #
      # Exemplary user for Johannes, copy&paste for more
      #
      - name: Create user for johannes
        action: user name=johannes state=present groups=sudo shell=/bin/bash

      - name: Change password for johannes
        action: shell usermod -p `openssl passwd {{ lookup('password', 'account/'+host+'/johannes length=23') }}` johannes executable='/bin/bash'

      - name: Create .ssh folder for johannes
        action: file path=/home/johannes/.ssh/ state=directory owner=johannes

      - name: Copy SSH key for johannes
        action: authorized_key key="{{ lookup('file', 'keys/johannes.pub') }}"
            user=johannes 
      
      #
      # End of per-user config
      #

      - name: Switch to torservers.net's recommended ssh config
        action: copy src=config/sshd_config dest=/etc/ssh/sshd_config backup=yes
        notify: restart ssh

  handlers:
      - name: restart ssh
        action: service name=ssh state=restarted
